#!/bin/bash

set -e

die() {
    echo $1
    exit 1
}

usage() {
    cat <<EOF
$0: <src_dir> [dst_dir] copies src_dir on local machine to the specified MASTER's dst_dir directory. If dst_dir is not mentioned, src_dir is used
EOF
}

if [ -f ./distcheck ]; then
    . ./distcheck
else
    distcheckpath=`which distcheck`
    if [ -f $distcheckpath ]; then
	. $distcheckpath
    else
	die "distcheck not in path, couldn't verify master and slave"
    fi
fi

if [ "$#" -lt 1 ]; then
    usage
    die "Incorrect usage"
fi

. ./machines.sh

src=`$SSH $MASTER "readlink -f $1"`
echo $src
if [ "$#" -ne 2 ]; then
    dst=`$SSH $MASTER "dirname $src"`
else
    dst=$2
fi
echo $dst
set -x
distcmd -s "rsync -aviz $MASTER:$src $dst/"
