#!/bin/bash

die() {
    echo $1
    exit 1
}

if [ -f ./machines.sh ]; then
   . ./machines.sh
fi

[ -e $MASTER ] && die "you must set MASTER to the hostname of the master node"
[ -e $SLAVES ] && die "you must set SLAVES to a whitespace-separated list of \
the hostnames of the slave nodes"

SSH_OPTS="-oStrictHostKeyChecking=no "
SSH="ssh SSH_OPTS"
RSYNC="rsync SSH_OPTS"
